const express=require("express");
const {addUser,authUser,fetchUser}=require("../contoller/userContoller");
const {addPost,getPost,getFeed,deletePost,likePost}=require("../contoller/postContoller");
const app=express();
const router=express.Router();
router.post("/signup",addUser);
router.post("/login",authUser);
router.post("/post",addPost);
router.post("/feed",getFeed);
router.get("/community/:community",getPost);
router.delete("/post/delete/:id",deletePost);
router.put("/post/likes/:id",likePost);
module.exports=router;